# Generated by Django 5.0.2 on 2024-09-19 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(max_length=500, upload_to='pdf/')),
                ('temas', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('assunto', models.CharField(blank=True, max_length=255, null=True)),
                ('filme', models.TextField(blank=True, null=True)),
                ('fonte', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Arquivos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
