# Generated by Django 5.0.2 on 2024-09-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leituranarede', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem_url', models.URLField(blank=True, null=True)),
                ('imagem_upload', models.ImageField(blank=True, null=True, upload_to='cartoes/')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=200)),
                ('ordem', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
