# Generated by Django 5.0.2 on 2024-09-25 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leituranarede', '0002_cartao'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartao',
            table='Cartões',
        ),
    ]
