# Generated by Django 5.0.2 on 2024-09-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leituranarede', '0003_alter_cartao_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='descricao',
            field=models.CharField(max_length=500),
        ),
    ]
