# Generated by Django 5.0.2 on 2024-09-25 18:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leituranarede', '0007_alter_cartao_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='descricao',
            field=ckeditor.fields.RichTextField(max_length=650),
        ),
    ]
